"""empty message

Revision ID: 063a01de6abc
Revises: 
Create Date: 2022-06-28 15:34:18.172679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063a01de6abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'city_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('weather', 'temp_c',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weather', 'temp_f',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('weather', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weather', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('weather', 'temp_f',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weather', 'temp_c',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weather', 'city_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
